#!/usr/bin/env bash
export PORT=3000
export MONGO_USER=admin
export MONGO_PASS=raziel
export MONGO_HOST=localhost
export MONGO_PORT=27017
export MONGO_DB=pdn
export MONGO_DBAUTH=admin
export MONGO_AUTHMECHANISM=SCRAM-SHA-1
yarn start
